name: render.yaml
on:
  push:
    branches: master
permissions:
  contents: write
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo
      - uses: actions/checkout@v4

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install R packages from files/DESCRIPTION
      - uses: r-lib/actions/setup-r-dependencies@v2

      # Install quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # Render the quarto file into html/
      - name: Render
        run: quarto render index.qmd --output-dir=html

      # Publish html/ to GitHub pages
      - name: Publish to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: html
